# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.cache/wt [current_project]
set_property parent.project_path C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/Oled_Display.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/Top_Cedric.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/Top_Graph.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/alt_coordinates.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/axis_ticks.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/bin32_to_bcd10.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/calc_integal.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/clock_divider_generic.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/compute_function.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/cursor.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/derivative_renderer_fixed.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/function_evaluator.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/gp_seg_controller.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/graph.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/graph_coord.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/graph_inputs.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/graph_menu.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/input_scaler.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/keypad_controller.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/led_controller.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/max_finder.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/max_select_controller.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/min_finder.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/oled_calc_display_text.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/oled_keypad_ui.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/oled_main_menu.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/oled_result_seq.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/pan_controller.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/seven_seg_display.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/sevenseg_text4.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/zoom_scale.v
  C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/sources_1/new/Top_Basys3.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/constrs_1/new/my_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/MALCOLM/Downloads/S2_06_Project.xpr/CedricGroup/CedricGroup.srcs/constrs_1/new/my_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Basys3 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Basys3.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Basys3_utilization_synth.rpt -pb Top_Basys3_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
